# Generated by Django 5.0 on 2025-04-14 22:26

import autoslug.fields
import django.db.models.deletion
import meta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Кольца, Серьги, Подвески', max_length=100, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='Автоматически генерируется из названия', populate_from='name', unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, help_text='Необязательное поле', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название товара', max_length=200, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(help_text='Подробное описание товара', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в рублях', max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 800x800px', upload_to='products/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать товар в каталоге?', verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('meta_title', models.CharField(blank=True, help_text='Заголовок для поисковых систем (до 60 символов)', max_length=60, verbose_name='Мета-заголовок (SEO)')),
                ('meta_description', models.CharField(blank=True, help_text='Краткое описание для сниппета (до 160 символов)', max_length=160, verbose_name='Мета-описание (SEO)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='product_slug_idx'), models.Index(fields=['price'], name='product_price_idx')],
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
