# Generated by Django 5.0 on 2025-05-15 21:30

import autoslug.fields
import django.db.models.deletion
import meta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Кольца, Серьги, Подвески', max_length=100, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, help_text='Необязательное поле', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название товара', max_length=200, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(help_text='Подробное описание товара', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в рублях', max_digits=10, verbose_name='Цена')),
                ('main_image', models.ImageField(default='products/main/images.png', help_text='Основное фото товара (рекомендуемый размер: 800x800px)', upload_to='products/main/', verbose_name='Главное изображение')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать товар в каталоге?', verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_featured', models.BooleanField(default=False, help_text='Показывать товар в рекомендуемых?', verbose_name='Рекомендуемый')),
                ('meta_title', models.CharField(blank=True, help_text='Заголовок для поисковых систем (до 60 символов)', max_length=60, verbose_name='Мета-заголовок (SEO)')),
                ('meta_description', models.CharField(blank=True, help_text='Краткое описание для сниппета (до 160 символов)', max_length=160, verbose_name='Мета-описание (SEO)')),
                ('available', models.BooleanField(default=True, help_text='Отметьте, если товар есть в наличии', verbose_name='В наличии')),
                ('is_custom', models.BooleanField(default=False, help_text='Если товар изготавливается индивидуально', verbose_name='Эксклюзивный заказ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Дополнительное фото товара', upload_to='products/gallery/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, help_text='Описание изображения для SEO', max_length=100, verbose_name='Alt-текст')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше фото в галерее', verbose_name='Порядок сортировки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='product_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='product_price_idx'),
        ),
    ]
