# Generated by Django 5.0 on 2025-04-15 16:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True, verbose_name='URL-адрес'),
        ),
    ]
